import { writeFile } from 'node:fs/promises';
import { effectMakerOperation } from '../extension/adapter.js';
import { mountEditorPanel, renderEditorPanel } from '../extension/editor-panel.js';
import { createOperationRuntime } from '../extension/runtime.js';
import { panelStyles } from '../extension/panel-styles.js';
import { startEditorJob } from '../extension/editor-job.js';

// Static classic-script bundle: no eval, remote code, global API or message bridge.
const bundle = '// Generated by scripts/build-panel.js. Edit the source modules.\n' +
  '(() => {\nconst createOperationRuntime = ' + createOperationRuntime.toString() + ';\n' +
  'const operation = ' + effectMakerOperation.toString() + ';\n' +
  'const panelStyles = ' + JSON.stringify(panelStyles) + ';\n' +
  'const renderEditorPanel = ' + renderEditorPanel.toString() + ';\n' +
  'const mount = ' + mountEditorPanel.toString() + ';\nreturn mount(operation);\n})();\n';
await writeFile(new URL('../extension/editor-panel.bundle.js', import.meta.url), bundle);

// A self-contained function for Chrome's documented executeScript({func}) API.
// The extension page never evaluates source strings at runtime.
const jobSource = startEditorJob.toString();
const bodyStart = jobSource.indexOf('{') + 1;
const jobBundle = '// Generated by scripts/build-panel.js. Edit editor-job.js.\nexport ' +
  jobSource.slice(0, bodyStart) + '\nconst createOperationRuntime = ' + createOperationRuntime.toString() + ';\n' +
  'const effectMakerOperation = ' + effectMakerOperation.toString() + ';\n' + jobSource.slice(bodyStart) + '\n';
await writeFile(new URL('../extension/editor-job.bundle.js', import.meta.url), jobBundle);
